// ─── Mock Data — Pro.Thodia.so ────────────────────────────────────────────────
// Source of truth cho toàn bộ demo data, aligned với z68-docs specs

// ─── Enums / Constants ────────────────────────────────────────────────────────
export const SERVICES = {
  bds: { label: "Bất động sản", schema: "RealEstateAgent", icon: "Building2" },
  "xe-co": { label: "Xe cộ", schema: "AutoDealer", icon: "Car" },
  "bao-hiem": { label: "Bảo hiểm", schema: "InsuranceAgency", icon: "Shield" },
} as const;

export const PROVINCES = {
  "tp-ho-chi-minh": "TP. Hồ Chí Minh",
  "ha-noi": "Hà Nội",
  "da-nang": "Đà Nẵng",
  "binh-duong": "Bình Dương",
  "dong-nai": "Đồng Nai",
  "can-tho": "Cần Thơ",
  "khanh-hoa": "Khánh Hòa",
  "long-an": "Long An",
};

// ─── Agents ───────────────────────────────────────────────────────────────────
export const AGENTS = [
  {
    slug: "nguyen-van-minh-bds-phuong-tan-thuan-tay",
    agent_type: "location-based" as const,
    name: "Nguyễn Văn Minh",
    title: "Môi giới BĐS Chuyên nghiệp",
    category: "bds",
    license: "CC-BĐS-HCM-2021-04782",
    license_issuer: "Sở Xây dựng TP.HCM",
    years_experience: 8,
    phone: "+84903456789",
    email: "minh.nguyen@bds.vn",
    working_hours: "Thứ 2 – Thứ 7: 08:00 – 18:00",
    rating: 4.8,
    review_count: 47,
    verified: true,
    province: "tp-ho-chi-minh",
    ward: "phuong-tan-thuan-tay",
    ward_label: "P. Tân Thuận Tây",
    legacy_district: "Quận 7",
    office_address: "123 Nguyễn Hữu Thọ, P. Tân Thuận Tây, TP.HCM",
    lat: 10.7285,
    lng: 106.7179,
    primary_brand: null,
    brand_tier: null,
    authorized_brands: [] as string[],
    photo: "/images/agents/nguyen-van-minh.jpg",
    gbp_url: "https://g.co/kgs/abc123",
    facebook_url: "https://facebook.com/nguyen.van.minh.bds",
    phone_zalo: "+84903456789",
    languages: ["Tiếng Việt"],
    area_served_ward: ["phuong-tan-thuan-tay", "phuong-tan-thuan-dong", "phuong-phu-thuan"],
    brand_certification_url: null as string | null,
    services: ["Mua bán căn hộ", "Cho thuê văn phòng", "Đất nền", "Nhà phố"],
    bio: "Với 8 năm kinh nghiệm chuyên sâu tại khu vực Quận 7 cũ (nay là P. Tân Thuận Tây), anh Minh đã tư vấn thành công hơn 200 giao dịch BĐS. Chuyên gia về phân khúc căn hộ cao cấp và đất nền ven sông.",
    achievements: ["Top 10 Môi giới Q.7 2024", "Chứng chỉ Định giá BĐS", "200+ giao dịch thành công"],
    portfolio: [
      { type: "Căn hộ", area: "P. Tân Thuận Tây", result: "Bán thành công, 3.2 tỷ", year: 2024 },
      { type: "Đất nền", area: "P. Phú Thuận", result: "Bán thành công, 5.8 tỷ", year: 2024 },
      { type: "Căn hộ cho thuê", area: "P. Tân Thuận Đông", result: "Cho thuê 18tr/tháng", year: 2023 },
    ],
    reviews: [
      { author: "Trần Thị Hoa", rating: 5, date: "2024-03-15", text: "Anh Minh tư vấn rất nhiệt tình, hỗ trợ pháp lý toàn trình. Mình mua được căn hộ ưng ý, giá tốt." },
      { author: "Lê Văn Đức", rating: 5, date: "2024-01-20", text: "Chuyên nghiệp, phản hồi nhanh, am hiểu thị trường Quận 7 rất sâu." },
      { author: "Nguyễn Phương Anh", rating: 4, date: "2023-11-08", text: "Tư vấn tốt, thủ tục nhanh. Sẽ giới thiệu cho bạn bè." },
    ],
    faq: [
      { question: "Anh Minh có kinh nghiệm ở khu vực nào?", answer: "Anh Minh chuyên về khu vực Phường Tân Thuận Tây, Phường Tân Thuận Đông và Phường Phú Thuận (khu vực Quận 7 cũ), TP.HCM với 8 năm kinh nghiệm." },
      { question: "Chi phí môi giới là bao nhiêu?", answer: "Chi phí môi giới thỏa thuận theo giao dịch, thông thường 1-2% giá trị hợp đồng. Tư vấn miễn phí lần đầu." },
      { question: "Có hỗ trợ vay ngân hàng không?", answer: "Có. Anh Minh hợp tác với các ngân hàng uy tín để hỗ trợ khách hàng vay mua BĐS với lãi suất tốt nhất." },
    ],
    featured: true,
  },
  {
    slug: "tran-thi-lan-vinfast-freelance",
    agent_type: "freelance" as const,
    name: "Trần Thị Lan",
    title: "Tư vấn Bán hàng VinFast",
    category: "xe-co",
    license: "VF-HCM-2023-0042",
    license_issuer: "VinFast Việt Nam",
    years_experience: 5,
    phone: "+84912345678",
    email: "lan.tran@vinfast.vn",
    working_hours: "Thứ 2 – Chủ nhật: 08:00 – 20:00",
    rating: 4.9,
    review_count: 82,
    verified: true,
    province: "tp-ho-chi-minh",
    ward: null,
    ward_label: null,
    legacy_district: null,
    office_address: null,
    lat: null,
    lng: null,
    primary_brand: "VinFast",
    brand_tier: "gold" as const,
    authorized_brands: ["VinFast"],
    photo: "/images/agents/tran-thi-lan.jpg",
    gbp_url: "https://g.co/kgs/xyz789",
    facebook_url: "https://facebook.com/tran.thi.lan.vinfast",
    phone_zalo: "+84912345678",
    languages: ["Tiếng Việt", "English"],
    area_served_ward: [] as string[],
    brand_certification_url: "https://vinfastauto.com/dai-ly-uy-quyen",
    services: ["Tư vấn mua xe VinFast", "Hỗ trợ vay vốn", "Thủ tục đăng ký xe", "Bảo hiểm xe"],
    bio: "Chuyên gia tư vấn VinFast với 5 năm kinh nghiệm. Chị Lan phục vụ khách hàng trên toàn TP.HCM và các tỉnh lân cận, cam kết đồng hành từ khi tư vấn đến khi nhận xe.",
    achievements: ["Top Sales VinFast HCM 2024", "500+ xe đã bàn giao", "Đại lý Vàng VinFast"],
    portfolio: [
      { type: "VinFast VF8", area: "TP.HCM", result: "Bàn giao 12 xe trong tháng", year: 2024 },
      { type: "VinFast VF6", area: "Bình Dương", result: "Bàn giao 20 xe", year: 2023 },
    ],
    reviews: [
      { author: "Hoàng Minh Tú", rating: 5, date: "2024-04-01", text: "Chị Lan tư vấn tại nhà mình rất tiện. Không cần ra showroom vẫn được hỗ trợ đầy đủ hồ sơ vay." },
      { author: "Phan Thị Ngọc", rating: 5, date: "2024-02-14", text: "Đại lý VinFast chính thức, giá niêm yết, không bị hét giá. Rất hài lòng." },
    ],
    faq: [
      { question: "Chị Lan có văn phòng hay showroom không?", answer: "Chị Lan là đại lý VinFast độc lập, phục vụ khách hàng tại địa chỉ của quý khách hoặc qua tư vấn online. Điều này giúp tiết kiệm thời gian di chuyển." },
      { question: "Giá xe VinFast mua qua đại lý độc lập có khác không?", answer: "Không. Giá xe VinFast theo niêm yết của hãng, đại lý độc lập hay showroom đều như nhau. Khách hàng nhận được hỗ trợ cá nhân hóa hơn." },
      { question: "Chị Lan có phải đại lý chính thức VinFast không?", answer: "Có. Chị Lan là đại lý ủy quyền chính thức của VinFast, mã đại lý VF-HCM-2023-0042, được VinFast cấp và xác nhận." },
    ],
    featured: true,
  },
  {
    slug: "le-thi-thu-ha-bds-phuong-thu-thiem",
    agent_type: "location-based" as const,
    name: "Lê Thị Thu Hà",
    title: "Chuyên viên BĐS Cao cấp",
    category: "bds",
    license: "CC-BĐS-HCM-2019-02341",
    license_issuer: "Sở Xây dựng TP.HCM",
    years_experience: 12,
    phone: "+84987654321",
    email: "thuha.le@bds.vn",
    working_hours: "Thứ 2 – Thứ 7: 08:00 – 18:00",
    rating: 4.9,
    review_count: 134,
    verified: true,
    province: "tp-ho-chi-minh",
    ward: "phuong-thu-thiem",
    ward_label: "P. Thủ Thiêm",
    legacy_district: "Quận 2",
    office_address: "45 Đỗ Quang, P. Thủ Thiêm, TP.HCM",
    lat: 10.7879,
    lng: 106.7321,
    primary_brand: null,
    brand_tier: null,
    authorized_brands: [] as string[],
    photo: "/images/agents/le-thi-thu-ha.jpg",
    gbp_url: "https://g.co/kgs/def456",
    facebook_url: null,
    phone_zalo: "+84987654321",
    languages: ["Tiếng Việt"],
    area_served_ward: ["phuong-thu-thiem", "phuong-an-phu", "phuong-binh-an"],
    brand_certification_url: null as string | null,
    services: ["BĐS khu Thủ Thiêm", "Căn hộ cao cấp", "Đầu tư BĐS", "Pháp lý BĐS"],
    bio: "12 năm kinh nghiệm tại khu vực Thủ Thiêm (Quận 2 cũ). Chuyên gia hàng đầu về phân khúc BĐS cao cấp khu Thủ Thiêm - Thành Thủ Đức.",
    achievements: ["Top Agent 2022-2024", "Chuyên gia BĐS Thủ Thiêm", "400+ giao dịch"],
    portfolio: [
      { type: "Căn hộ cao cấp", area: "P. Thủ Thiêm", result: "Bán 8.5 tỷ", year: 2024 },
      { type: "Đất nền Thủ Thiêm", area: "P. An Phú", result: "Bán 12 tỷ", year: 2023 },
    ],
    reviews: [
      { author: "Nguyễn Văn Hùng", rating: 5, date: "2024-05-01", text: "Chị Hà am hiểu thị trường Thủ Thiêm rất sâu, hỗ trợ pháp lý rất tốt." },
      { author: "Bùi Thị Mai", rating: 5, date: "2024-03-10", text: "Chuyên nghiệp, minh bạch. Mua được căn hộ ưng ý nhờ chị Hà tư vấn." },
    ],
    faq: [
      { question: "Chị Hà chuyên BĐS khu vực nào?", answer: "Chị Hà chuyên khu vực Thủ Thiêm, An Phú, Bình An (khu Quận 2 cũ) với 12 năm kinh nghiệm." },
      { question: "Có hỗ trợ pháp lý sang tên không?", answer: "Có. Chị Hà hỗ trợ toàn bộ thủ tục pháp lý, sang tên, công chứng, giúp khách hàng an tâm từ A-Z." },
    ],
    featured: true,
  },
  {
    slug: "pham-quoc-bao-bao-hiem-ha-noi",
    agent_type: "freelance" as const,
    name: "Phạm Quốc Bảo",
    title: "Tư vấn Bảo hiểm Manulife",
    category: "bao-hiem",
    license: "BH-HN-2020-00912",
    license_issuer: "Cục Quản lý & Giám sát Bảo hiểm",
    years_experience: 7,
    phone: "+84966123456",
    email: "bao.pham@manulife.com.vn",
    working_hours: "Thứ 2 – Thứ 6: 08:30 – 17:30",
    rating: 4.7,
    review_count: 56,
    verified: true,
    province: "ha-noi",
    ward: null,
    ward_label: null,
    legacy_district: null,
    office_address: null,
    lat: null,
    lng: null,
    primary_brand: "Manulife",
    brand_tier: "silver" as const,
    authorized_brands: ["Manulife"],
    photo: "/images/agents/pham-quoc-bao.jpg",
    gbp_url: null,
    facebook_url: "https://facebook.com/pham.quoc.bao.manulife",
    phone_zalo: "+84966123456",
    languages: ["Tiếng Việt", "English"],
    area_served_ward: [] as string[],
    brand_certification_url: "https://manulife.com.vn/dai-ly-chinh-thuc",
    services: ["Bảo hiểm nhân thọ", "Bảo hiểm sức khỏe", "Bảo hiểm xe", "Đầu tư bảo hiểm"],
    bio: "7 năm kinh nghiệm tư vấn bảo hiểm Manulife tại Hà Nội. Anh Bảo đã giúp hơn 300 khách hàng lựa chọn sản phẩm bảo hiểm phù hợp nhất.",
    achievements: ["MDRT 2023", "Top Agent Manulife HN", "300+ hợp đồng"],
    portfolio: [
      { type: "Bảo hiểm nhân thọ", area: "Hà Nội", result: "150+ hợp đồng/năm", year: 2024 },
    ],
    reviews: [
      { author: "Vũ Thị Lan", rating: 5, date: "2024-02-20", text: "Anh Bảo tư vấn rõ ràng, không ép mua. Chọn được gói bảo hiểm phù hợp với thu nhập." },
      { author: "Đỗ Quang Huy", rating: 4, date: "2023-12-15", text: "Chuyên nghiệp, phục vụ tận tâm. Sẽ giới thiệu thêm khách hàng." },
    ],
    faq: [
      { question: "Anh Bảo tư vấn bảo hiểm hãng nào?", answer: "Anh Bảo là đại lý ủy quyền của Manulife Việt Nam, chuyên tư vấn toàn bộ sản phẩm bảo hiểm nhân thọ, sức khỏe và xe cộ của Manulife." },
      { question: "Phí bảo hiểm nhân thọ là bao nhiêu?", answer: "Phí bảo hiểm tùy thuộc vào độ tuổi, sức khỏe và nhu cầu của khách hàng. Liên hệ anh Bảo để được tư vấn và tính phí miễn phí." },
    ],
    featured: false,
  },
  {
    slug: "vo-minh-khoa-vinfast-da-nang",
    agent_type: "location-based" as const,
    name: "Võ Minh Khoa",
    title: "Trưởng phòng Kinh doanh VinFast Đà Nẵng",
    category: "xe-co",
    license: null,
    license_issuer: null,
    years_experience: 6,
    phone: "+84935678901",
    email: "khoa.vo@vinfast.vn",
    working_hours: "Thứ 2 – Chủ nhật: 08:00 – 20:00",
    rating: 4.6,
    review_count: 38,
    verified: true,
    province: "da-nang",
    ward: "phuong-hai-chau-1",
    ward_label: "P. Hải Châu 1",
    legacy_district: "Q. Hải Châu",
    office_address: "200 Trần Phú, P. Hải Châu 1, Đà Nẵng",
    lat: 16.0544,
    lng: 108.2022,
    primary_brand: "VinFast",
    brand_tier: "silver" as const,
    authorized_brands: ["VinFast"],
    photo: "/images/agents/vo-minh-khoa.jpg",
    gbp_url: null,
    facebook_url: null,
    phone_zalo: "+84935678901",
    languages: ["Tiếng Việt"],
    area_served_ward: ["phuong-hai-chau-1", "phuong-hai-chau-2"],
    brand_certification_url: "https://vinfastauto.com/dai-ly-uy-quyen",
    services: ["Bán xe VinFast", "Xe trưng bày", "Hỗ trợ tài chính", "Dịch vụ sau bán"],
    bio: "Trưởng phòng kinh doanh VinFast Đà Nẵng với 6 năm kinh nghiệm. Anh Khoa chuyên phục vụ khách hàng miền Trung từ Quảng Nam đến Quảng Ngãi.",
    achievements: ["Best Showroom Miền Trung 2024", "150+ xe/năm", "Đại lý Bạc VinFast"],
    portfolio: [
      { type: "VinFast VF7", area: "Đà Nẵng", result: "Top doanh số miền Trung", year: 2024 },
    ],
    reviews: [
      { author: "Ngô Thị Hương", rating: 5, date: "2024-04-10", text: "Anh Khoa tư vấn nhiệt tình, lái thử nhanh chóng. Rất hài lòng với dịch vụ." },
      { author: "Trương Văn Bình", rating: 4, date: "2024-01-05", text: "Showroom đẹp, nhân viên chuyên nghiệp. Nhận xe đúng hẹn." },
    ],
    faq: [
      { question: "Showroom VinFast Đà Nẵng ở đâu?", answer: "Showroom tại 200 Trần Phú, Phường Hải Châu 1 (khu vực Quận Hải Châu cũ), Đà Nẵng. Mở cửa 7 ngày/tuần." },
      { question: "Có được lái thử miễn phí không?", answer: "Có. Khách hàng được lái thử miễn phí tất cả dòng xe VinFast. Đặt lịch qua số hotline hoặc Zalo." },
    ],
    featured: false,
  },
];

// ─── Locations ────────────────────────────────────────────────────────────────
export const LOCATIONS = [
  {
    slug: "showroom-vinfast-nguyen-van-linh",
    name: "Showroom VinFast Nguyễn Văn Linh",
    verified: true,
    image: "https://pro.thodia.so/images/showroom-vinfast-q7.jpg",
    category: "xe-co",
    schema_type: "AutoDealer",
    province: "tp-ho-chi-minh",
    phuong: "phuong-tan-thuan-tay",
    ward_label: "Phường Tân Thuận Tây",
    legacy_district: "Quận 7",
    // PostalAddress tách riêng (F3)
    street_address: "456 Nguyễn Văn Linh",
    address: "456 Nguyễn Văn Linh, Phường Tân Thuận Tây, TP. Hồ Chí Minh",
    postal_code: "700000",
    phone: "+84-28-3456-7890",
    email: "showroom.q7@vinfast.vn",
    rating: 4.7,
    review_count: 134,
    lat: 10.7285,
    lng: 106.7179,
    primary_brand: "VinFast",
    brand_tier: "gold" as const,
    is_authorized: true,
    // Display (text)
    opening_hours: [
      { day: "Thứ 2 – Thứ 6", hours: "08:00–18:00" },
      { day: "Thứ 7 – CN", hours: "08:00–17:00" },
    ],
    // Schema.org chuẩn OpeningHoursSpecification (F1)
    opening_hours_spec: [
      { dayOfWeek: ["Monday","Tuesday","Wednesday","Thursday","Friday"], opens: "08:00", closes: "18:00" },
      { dayOfWeek: ["Saturday","Sunday"], opens: "08:00", closes: "17:00" },
    ],
    gbp_url: "https://maps.google.com/?cid=showroom-vinfast-nguyen-van-linh",
    facebook_page_url: "https://facebook.com/VinFastNguyenVanLinh",
    zalo_oa_url: "https://zalo.me/vinfast-nguyen-van-linh",
    phone_secondary: "+84-28-3456-7891",
    photo_exterior: ["https://pro.thodia.so/images/vinfast-q7-exterior-1.jpg"],
    photo_interior: ["https://pro.thodia.so/images/vinfast-q7-interior-1.jpg"],
    photo_team: ["https://pro.thodia.so/images/vinfast-q7-team-1.jpg"],
    services: ["Tư vấn & mua bán xe VinFast", "Hỗ trợ vay ngân hàng", "Bảo hiểm xe", "Lái thử miễn phí"],
    area_served: [
      { ward: "Phường Tân Thuận Tây", legacy: "Quận 7" },
      { ward: "Phường Tân Thuận Đông", legacy: "Quận 7" },
      { ward: "Phường Phú Thuận", legacy: "Quận 7" },
    ],
    // Reviews cho JSON-LD (F5)
    reviews: [
      { author: "Lê Hoàng Nam", rating: 5, date: "2024-04-10", text: "Showroom rộng rãi, nhân viên tư vấn nhiệt tình. Mua được VF3 giá tốt, thủ tục nhanh." },
      { author: "Phạm Thị Bích", rating: 5, date: "2024-03-22", text: "Dịch vụ chuyên nghiệp, hỗ trợ vay ngân hàng rất thuận tiện. Sẽ giới thiệu bạn bè." },
      { author: "Nguyễn Minh Tuấn", rating: 4, date: "2024-02-15", text: "Xe đẹp, giá minh bạch. Chờ giao xe hơi lâu một chút." },
    ],
    faq: [
      { question: "Showroom có xe VF3 để xem thực tế không?", answer: "Có. Showroom luôn trưng bày đầy đủ các dòng xe VinFast hiện hành, bao gồm VF3, VF5, VF7, VF8, VF9." },
      { question: "Giá xe VinFast tại showroom có khác giá niêm yết không?", answer: "Không. Showroom cam kết bán đúng giá niêm yết của VinFast. Mọi ưu đãi đều được thông báo chính thức từ hãng." },
      { question: "Có hỗ trợ vay ngân hàng mua xe không?", answer: "Có. Showroom hợp tác với nhiều ngân hàng, hỗ trợ vay tới 90% giá trị xe, lãi suất ưu đãi từ 7.5%/năm." },
    ],
    featured: true,
  },
  {
    slug: "van-phong-bds-nguyen-van-minh",
    name: "Văn phòng BĐS Nguyễn Văn Minh",
    verified: true,
    image: "https://pro.thodia.so/images/vp-bds-tan-thuan.jpg",
    category: "bds",
    schema_type: "RealEstateAgent",
    province: "tp-ho-chi-minh",
    phuong: "phuong-tan-thuan-tay",
    ward_label: "Phường Tân Thuận Tây",
    legacy_district: "Quận 7",
    street_address: "123 Nguyễn Hữu Thọ",
    address: "123 Nguyễn Hữu Thọ, Phường Tân Thuận Tây, TP. Hồ Chí Minh",
    postal_code: "700000",
    phone: "+84903456789",
    email: "minh@bds-q7.vn",
    rating: 4.8,
    review_count: 47,
    lat: 10.728,
    lng: 106.717,
    primary_brand: null,
    brand_tier: null,
    is_authorized: false,
    opening_hours: [
      { day: "Thứ 2 – Thứ 7", hours: "08:00–18:00" },
    ],
    opening_hours_spec: [
      { dayOfWeek: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"], opens: "08:00", closes: "18:00" },
    ],
    gbp_url: "https://maps.google.com/?cid=vp-bds-q7-minh",
    facebook_page_url: "https://facebook.com/BDSNguyenVanMinhQ7",
    zalo_oa_url: "https://zalo.me/bds-nguyen-van-minh",
    phone_secondary: null as string | null,
    photo_exterior: ["https://pro.thodia.so/images/vp-bds-q7-exterior.jpg"],
    photo_interior: [] as string[],
    photo_team: [] as string[],
    services: ["Mua bán căn hộ", "Cho thuê văn phòng", "Tư vấn đầu tư", "Pháp lý BĐS"],
    area_served: [
      { ward: "Phường Tân Thuận Tây", legacy: "Quận 7" },
      { ward: "Phường Tân Thuận Đông", legacy: "Quận 7" },
    ],
    reviews: [
      { author: "Trần Văn Hùng", rating: 5, date: "2024-05-01", text: "Anh Minh tư vấn rất chi tiết, hỗ trợ pháp lý toàn trình. Mua được căn hộ ưng ý." },
      { author: "Võ Thị Lan", rating: 5, date: "2024-03-18", text: "Chuyên nghiệp, thị trường khu Q.7 rất am hiểu. Sẽ tìm lại khi cần." },
      { author: "Lý Minh Châu", rating: 4, date: "2024-01-09", text: "Tư vấn tốt, thủ tục nhanh. Giá tư vấn hợp lý." },
    ],
    faq: [
      { question: "Môi giới tính phí như thế nào?", answer: "Thông thường phí môi giới là 1-2% giá trị giao dịch, trả một lần khi ký hợp đồng mua bán thành công." },
      { question: "Có hỗ trợ kiểm tra pháp lý trước khi mua không?", answer: "Có. Văn phòng cung cấp dịch vụ kiểm tra pháp lý toàn diện trước khi ký hợp đồng, đảm bảo sổ hồng/sổ đỏ hợp lệ." },
    ],
    featured: true,
  },
  {
    slug: "showroom-honda-bach-dang-da-nang",
    name: "Honda Ô tô Bạch Đằng Đà Nẵng",
    verified: true,
    image: "https://pro.thodia.so/images/showroom-honda-danang.jpg",
    category: "xe-co",
    schema_type: "AutoDealer",
    province: "da-nang",
    phuong: "phuong-hai-chau-1",
    ward_label: "Phường Hải Châu 1",
    legacy_district: "Quận Hải Châu",
    street_address: "125 Bạch Đằng",
    address: "125 Bạch Đằng, Phường Hải Châu 1, Đà Nẵng",
    postal_code: "550000",
    phone: "+842363456789",
    email: "showroom@honda-danang.vn",
    rating: 4.5,
    review_count: 89,
    lat: 16.0546,
    lng: 108.2025,
    primary_brand: "Honda",
    brand_tier: "gold" as const,
    is_authorized: true,
    opening_hours: [
      { day: "Thứ 2 – Thứ 7", hours: "07:30–18:00" },
      { day: "Chủ nhật", hours: "08:00–17:00" },
    ],
    opening_hours_spec: [
      { dayOfWeek: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"], opens: "07:30", closes: "18:00" },
      { dayOfWeek: ["Sunday"], opens: "08:00", closes: "17:00" },
    ],
    gbp_url: "https://maps.google.com/?cid=honda-bach-dang-danang",
    facebook_page_url: "https://facebook.com/HondaBachDangDaNang",
    zalo_oa_url: "https://zalo.me/honda-bach-dang",
    phone_secondary: "+842363456790",
    photo_exterior: ["https://pro.thodia.so/images/honda-danang-exterior.jpg"],
    photo_interior: ["https://pro.thodia.so/images/honda-danang-interior.jpg"],
    photo_team: [] as string[],
    services: ["Bán xe Honda mới", "Xe cũ chính hãng", "Dịch vụ bảo dưỡng", "Phụ tùng chính hãng"],
    area_served: [
      { ward: "Phường Hải Châu 1", legacy: "Quận Hải Châu" },
      { ward: "Phường Hải Châu 2", legacy: "Quận Hải Châu" },
    ],
    reviews: [
      { author: "Đặng Văn Bình", rating: 5, date: "2024-04-05", text: "Dịch vụ bảo dưỡng Honda tốt, nhanh và giá chuẩn hãng." },
      { author: "Phan Thị Hoa", rating: 4, date: "2024-02-28", text: "Nhân viên nhiệt tình, showroom sạch đẹp. Mua HR-V giá tốt." },
    ],
    faq: [
      { question: "Showroom có bán xe Honda cũ chính hãng không?", answer: "Có. Showroom có chương trình xe Honda đã qua sử dụng được kiểm tra kỹ thuật và bảo hành từ hãng." },
      { question: "Dịch vụ bảo dưỡng có cần đặt lịch trước không?", answer: "Khuyến khích đặt lịch trước để giảm thời gian chờ. Có thể đặt qua hotline hoặc Zalo OA." },
    ],
    featured: false,
  },
];

// ─── Brands ───────────────────────────────────────────────────────────────────
export const BRANDS = [
  {
    slug: "vinfast",
    name: "VinFast",
    category: "xe-co",
    website: "https://vinfastauto.com",
    tagline: "Xe điện Việt Nam — Tiên phong & Đổi mới",
    description: "VinFast là thương hiệu xe ô tô điện của Việt Nam thuộc Vingroup. Thành lập 2017, đã xuất khẩu đến 14 quốc gia. Mạng lưới đại lý phủ 63 tỉnh thành.",
    stats: { dealers: 187, provinces: 34, agents: 412 },
    founding_year: 2017,
    country_origin: "VN",
    headquarters: "Hải Phòng, Việt Nam",
    logo_initial: "VF",
  },
  {
    slug: "honda",
    name: "Honda",
    category: "xe-co",
    website: "https://hondaoto.com.vn",
    tagline: "The Power of Dreams",
    description: "Honda Ô tô Việt Nam với mạng lưới đại lý chính hãng trên toàn quốc. Chuyên các dòng xe phổ thông đến SUV cao cấp.",
    stats: { dealers: 143, provinces: 28, agents: 286 },
    founding_year: 1948,
    country_origin: "JP",
    headquarters: "Tokyo, Nhật Bản",
    logo_initial: "H",
  },
  {
    slug: "toyota",
    name: "Toyota",
    category: "xe-co",
    website: "https://toyota.com.vn",
    tagline: "Let's Go Places",
    description: "Toyota Việt Nam — thương hiệu xe Nhật Bản uy tín nhất tại Việt Nam với hơn 30 năm kinh doanh.",
    stats: { dealers: 98, provinces: 22, agents: 210 },
    founding_year: 1937,
    country_origin: "JP",
    headquarters: "Toyota, Aichi, Nhật Bản",
    logo_initial: "T",
  },
  {
    slug: "manulife",
    name: "Manulife",
    category: "bao-hiem",
    website: "https://manulife.com.vn",
    tagline: "Quyết định khôn ngoan. Sống tốt hơn.",
    description: "Manulife Việt Nam — công ty bảo hiểm nhân thọ Canada, hoạt động tại VN từ 1999. Mạng lưới 40.000+ đại lý toàn quốc.",
    stats: { dealers: 76, provinces: 63, agents: 40000 },
    founding_year: 1887,
    country_origin: "CA",
    headquarters: "Toronto, Canada",
    logo_initial: "M",
  },
  {
    slug: "prudential",
    name: "Prudential",
    category: "bao-hiem",
    website: "https://prudential.com.vn",
    tagline: "Luôn luôn lắng nghe. Luôn luôn thấu hiểu.",
    description: "Prudential Việt Nam hoạt động từ 1999 với hơn 300 văn phòng đại lý. Chuyên bảo hiểm nhân thọ, sức khỏe và đầu tư.",
    stats: { dealers: 65, provinces: 63, agents: 35000 },
    founding_year: 1848,
    country_origin: "GB",
    headquarters: "London, Anh Quốc",
    logo_initial: "P",
  },
  {
    slug: "vinhomes",
    name: "Vinhomes",
    category: "bds",
    website: "https://vinhomes.vn",
    tagline: "Nơi đáng sống nhất Việt Nam",
    description: "Vinhomes — chủ đầu tư BĐS hàng đầu Việt Nam thuộc Vingroup. Các dự án tại Hà Nội, TP.HCM và nhiều tỉnh thành.",
    stats: { dealers: 54, provinces: 12, agents: 5000 },
    founding_year: 2008,
    country_origin: "VN",
    headquarters: "Hà Nội, Việt Nam",
    logo_initial: "VH",
  },
];

// ─── Geo Clusters (tên địa danh cũ → phường mới) ──────────────────────────────
export const GEO_CLUSTERS = [
  {
    province: "tp-ho-chi-minh",
    slug: "khu-vuc-quan-7",
    label: "Khu vực Quận 7",
    legacy_name: "Quận 7",
    wards: [
      { slug: "phuong-tan-thuan-tay", label: "P. Tân Thuận Tây", count: 18 },
      { slug: "phuong-tan-thuan-dong", label: "P. Tân Thuận Đông", count: 12 },
      { slug: "phuong-phu-thuan", label: "P. Phú Thuận", count: 8 },
      { slug: "phuong-binh-thuan", label: "P. Bình Thuận", count: 5 },
    ],
  },
  {
    province: "tp-ho-chi-minh",
    slug: "khu-vuc-quan-2",
    label: "Khu vực Quận 2",
    legacy_name: "Quận 2",
    wards: [
      { slug: "phuong-thu-thiem", label: "P. Thủ Thiêm", count: 15 },
      { slug: "phuong-an-phu", label: "P. An Phú", count: 11 },
      { slug: "phuong-binh-an", label: "P. Bình An", count: 7 },
    ],
  },
];

// ─── Homepage stats ───────────────────────────────────────────────────────────
export const SITE_STATS = {
  agents: 1847,
  locations: 423,
  brands: 28,
  provinces: 34,
  verified_pct: 94,
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function getFeaturedAgents() {
  return AGENTS.filter((a) => a.featured);
}

export function getFeaturedLocations() {
  return LOCATIONS.filter((l) => l.featured);
}

export function getAgentsByProvince(province: string) {
  return AGENTS.filter((a) => a.province === province);
}

export function getAgentsByService(service: string) {
  return AGENTS.filter((a) => a.category === service);
}

export function getLocationsByProvince(province: string) {
  return LOCATIONS.filter((l) => l.province === province);
}

export function getServiceLabel(service: string): string {
  return SERVICES[service as keyof typeof SERVICES]?.label ?? service;
}

export function getProvinceLabel(province: string): string {
  return PROVINCES[province as keyof typeof PROVINCES] ?? province;
}

// ─── Province geo data (ISO 3166-2:VN codes + centroid coords) ────────────────
export const PROVINCE_GEO: Record<string, { iso: string; lat: number; lng: number }> = {
  "tp-ho-chi-minh": { iso: "VN-SG", lat: 10.8231, lng: 106.6297 },
  "ha-noi":          { iso: "VN-HN", lat: 21.0285, lng: 105.8542 },
  "da-nang":         { iso: "VN-DN", lat: 16.0544, lng: 108.2022 },
  "binh-duong":      { iso: "VN-BD", lat: 11.0686, lng: 106.6521 },
  "dong-nai":        { iso: "VN-39", lat: 10.9490, lng: 106.8143 },
  "can-tho":         { iso: "VN-CT", lat: 10.0452, lng: 105.7469 },
  "khanh-hoa":       { iso: "VN-34", lat: 12.2388, lng: 109.1967 },
  "long-an":         { iso: "VN-41", lat: 10.6956, lng: 106.2431 },
};
